title: 31st of February
name: 31st of February
email: ""
description: >-
  A solo glitch-loop RPG of autistic burnout, routine, and escape.
baseurl: "/31st-of-feb-zine"
url: "https://mama-cailleach.github.io"
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  - jekyll-feed

search_enabled: true
heading_anchors: true

aux_links:
  "View on GitHub":
    - "https://github.com/mama-cailleach/31st-of-feb-zine"
